#!/usr/bin/perl
$/=undef;
open(FH,"protein.fasta");
$Protein=<FH>;
$a=($Protein=~tr/A//);
$c=($Protein=~tr/C//);
$d=($Protein=~tr/D//);
$e=($Protein=~tr/E//);
$f=($Protein=~tr/F//);
$g=($Protein=~tr/G//);
$h=($Protein=~tr/H//);
$i=($Protein=~tr/I//);
$k=($Protein=~tr/K//);
$l=($Protein=~tr/L//);
$m=($Protein=~tr/M//);
$n=($Protein=~tr/N//);
$p=($Protein=~tr/P//);
$q=($Protein=~tr/Q//);
$r=($Protein=~tr/R//);
$s=($Protein=~tr/S//);
$t=($Protein=~tr/T//);
$v=($Protein=~tr/V//);
$w=($Protein=~tr/W//);
$y=($Protein=~tr/Y//);
print "Amino acid count:\nA=$a";
print "\nC=$c";
print "\nD=$d";
print "\nE=$e";
print "\nF=$f";
print "\nG=$g";
print "\nH=$h";
print "\nI=$i";
print "\nK=$k";
print "\nL=$l";
print "\nM=$m";
print "\nN=$n";
print "\nP=$p";
print "\nQ=$q";
print "\nR=$r";
print "\nS=$s";
print "\nT=$t";
print "\nV=$v";
print "\nW=$w";
print "\nY=$y";

